export const PROTECTED_PATHS = [
  {
    test: (p) => /^(ios|android)\//.test(p),
    why: 'ios/ and android/ are generated by `expo prebuild` (CNG). Change app.config.ts or a config plugin instead.',
  },
  {
    test: (p) => p === 'yarn.lock' || p === 'package-lock.json',
    why: 'Lockfiles are managed by yarn. Run `yarn add` / `yarn expo install` instead.',
  },
  { test: (p) => p.startsWith('.yarn/releases/'), why: 'The vendored yarn release is managed by `yarn set version`.' },
  {
    test: (p) => /(^|\/)\.env(\..+)?$/.test(p) && !p.endsWith('.env.example'),
    why: 'Env files hold secrets. Edit .env.example and let the user fill in values.',
  },
  { test: (p) => p.startsWith('.expo/') || p.startsWith('node_modules/'), why: 'Generated directory.' },
  { test: (p) => p === 'expo-env.d.ts' || p === 'nativewind-env.d.ts', why: 'Generated by Expo.' },
];

const LAYERS = ['app', 'features', 'shared', 'theme', 'core'];

const FORBIDDEN_LAYER_IMPORTS = {
  core: ['app', 'features', 'shared', 'theme'],
  theme: ['app', 'features', 'shared'],
  shared: ['app', 'features'],
  features: ['app'],
  app: [],
};

function layerOf(projectPath) {
  const match = /^src\/([^/]+)\//.exec(projectPath);
  return match && LAYERS.includes(match[1]) ? match[1] : null;
}

function featureOf(projectPath) {
  const match = /^src\/features\/([^/]+)\//.exec(projectPath);
  return match ? match[1] : null;
}

function* importsOf(code) {
  const re =
    /(?:import|export)\s+(?:type\s+)?([\s\S]*?)\s+from\s+['"]([^'"]+)['"]|import\s+['"]([^'"]+)['"]|require\(\s*['"]([^'"]+)['"]\s*\)/g;
  let m;
  while ((m = re.exec(code))) {
    yield { clause: m[1] ?? '', source: m[2] ?? m[3] ?? m[4] };
  }
}

export function checkSource(projectPath, code) {
  if (!/^src\/.*\.(ts|tsx)$/.test(projectPath)) return [];
  const violations = [];
  const layer = layerOf(projectPath);
  const feature = featureOf(projectPath);
  const inTransport = projectPath.startsWith('src/core/ble/transport/');

  for (const { clause, source } of importsOf(code)) {
    if (source === 'react-native' && /\bStyleSheet\b/.test(clause)) {
      violations.push("Import `StyleSheet` from 'react-native-unistyles', never from 'react-native'.");
    }
    if (/^(uniwind|nativewind|heroui-native|tailwind-variants|tailwind-merge|clsx)(\/|$)/.test(source)) {
      violations.push(`\`${source}\` is banned: styling is Unistyles v3 only (see .claude/rules/unistyles.md).`);
    }
    if (source.startsWith('@react-navigation/')) {
      violations.push(
        `\`${source}\` is banned: expo-router forked React Navigation since SDK 56. Import from 'expo-router' instead.`,
      );
    }
    if (source === '@react-native-async-storage/async-storage') {
      violations.push('AsyncStorage is banned: persist through MMKV via `@/core/storage`.');
    }
    if (/^react-native-ble-(nitro|plx)(\/|$)/.test(source) && !inTransport) {
      violations.push(
        `\`${source}\` may only be imported in src/core/ble/transport/. Use the public API of \`@/core/ble\`.`,
      );
    }
    const alias = /^@\/([^/]+)(?:\/(.*))?$/.exec(source);
    if (alias && layer) {
      const [, targetLayer, rest] = alias;
      if (FORBIDDEN_LAYER_IMPORTS[layer]?.includes(targetLayer)) {
        violations.push(
          `Layer violation: src/${layer} must not import \`${source}\` (allowed direction: app → features → shared → theme → core).`,
        );
      }
      if (targetLayer === 'features' && rest?.includes('/')) {
        violations.push(
          `Deep import \`${source}\`: import other features only through their public \`@/features/<name>\` index.`,
        );
      }
      if (targetLayer === 'features' && feature && rest?.split('/')[0] === feature) {
        violations.push(
          `\`${source}\` imports the current feature through its alias: use a relative import inside a feature.`,
        );
      }
    }
  }
  return [...new Set(violations)];
}
